version: '3'
services: 
    node-app: 
        restart     : 'always'
        build       : 
            context     : '.'
            dockerfile  : Dockerfile.dev
            args        : 
                buildno: 1 
        volumes: 
            - /app/node-modules
            - ./:/app
        ports       : 
            - "3000:3000"
    tests: 
        build       : 
            context     : '.'
            dockerfile  : Dockerfile.dev
            args        : 
                buildno: 1 
        volumes: 
            - /app/node-modules
            - ./:/app
        command: ["npm","run","test"] 
